quarkus:
  management:
    enabled: true
    port: ${openfs.management.port}
    test-port: 9081
  http:
    port: ${openfs.http.port}
    test-port: 9082
    record-request-start-time: true
    access-log:
      enabled: ${openfs.log.access}
      category: openfs.api.access-log
      pattern: "%m %U %s %D ms"

openfs:
  management:
    port: 8081
  http:
    port: 8082
  s3:
    port: 8083
    virtual-threads-pool-size: 10
  data:
    path: /data
  log:
    access: true

"%dev":
  openfs:
    data:
      path: /tmp/openfs-data
  quarkus:
    log:
      category:
        "br.com.ordnaelmedeiros.openfs":
          level: DEBUG
